### ISSUE TITLE
Testing with iCloud3 and the IOS app

### ISSUE THREAD

**Issue by andystewart999** [gcobb321/icloud3_v1.0.6#76]
Hi - I've installed iCloud3 and everything appears to be working as expected... I had to rename the IOS App v2 device tracker name as called out [here](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud-account).

One question I have is that now I've renamed the IOS App device tracker name I don't seem to get any 'state change/zone change' events any more.  iCloud3 is eventing as expected but nothing via the IOS app and/or the device_tracker.andy_s_iphone_iosappv2 object.

Is that expected?  I wanted to compare the two and see what kind of location-based events I got from both sources, and compare the time deltas, accuracy etc.

Thanks all,
Andy

**Comment by gcobb321** [comment]
iCloud3 was updated to v2 last year. The repository you have posted the issue on is long dead. The latest general release is v2.0.5 and will be updated to v2.0.6 shortly. If you have not updated to v2, you will need to do so to work with the iOS app. There are a number of breaking changes going from v1 to v2 and you might want to look at the old release notes on the original v2.0 release.

**Comment by andystewart999** [comment]
oops, sorry about that... I didn't realise I was in the wrong context.  I'll repost under 2.0.5 (which I'm running).

Cheers,
andy
